- name: Enable the plugins is installed
  rabbitmq_plugin:
    names: "{{ item }}"
    prefix: /usr/lib/rabbitmq
    state: enabled
    new_only: "{{ rabbitmq_plugins_new_only }}"
  with_items: "{{ rabbitmq_plugins }}"